/*
 *  _ialias.h    Automatic include aliases
 *
 * =========================================================================
 *
 *                          Open Watcom Project
 *
 * Copyright (c) 2004-2016 The Open Watcom Contributors. All Rights Reserved.
 *
 *    This file is automatically generated. Do not edit directly.
 *
 * =========================================================================
 */
#ifndef __IALIAS_H_INCLUDED
#define __IALIAS_H_INCLUDED

#ifndef _ENABLE_AUTODEPEND
 #pragma read_only_file;
#endif

#pragma include_alias( <algorithm>,          <algorith>   )
#pragma include_alias( <cinttypes>,          <cinttype>   )
#pragma include_alias( <condition_variable>, <conditio>   )
#pragma include_alias( <exception>,          <exceptio>   )
#pragma include_alias( <exception.h>,        <exceptio.h> )
#pragma include_alias( <forward_list>,       <forward_>   )
#pragma include_alias( <functional>,         <function>   )
#pragma include_alias( <initializer_list>,   <initiali>   )
#pragma include_alias( <semaphore.h>,        <semaphor.h> )
#pragma include_alias( <stdexcept>,          <stdexcep>   )
#pragma include_alias( <stdexcept.h>,        <stdexcep.h> )
#pragma include_alias( <streambuf>,          <streambu>   )
#pragma include_alias( <streambuf.h>,        <streambu.h> )
#pragma include_alias( <strstream>,          <strstrea>   )
#pragma include_alias( <strstream.h>,        <strstrea.h> )
#pragma include_alias( <system_error>,       <system_e>   )
#pragma include_alias( <typeindex>,          <typeinde>   )
#pragma include_alias( <type_traits>,        <type_tra>   )
#pragma include_alias( <unordered_map>,      <unorderm>   )
#pragma include_alias( <unordered_set>,      <unorders>   )

#endif /* __IALIAS_H_INCLUDED */
