/*
 *  setjmpex.h
 *
 * =========================================================================
 *
 *                          Open Watcom Project
 *
 * Copyright (c) 2002-2016 The Open Watcom Contributors. All Rights Reserved.
 * Portions Copyright (c) 1983-2002 Sybase, Inc. All Rights Reserved.
 *
 *    This file is automatically generated. Do not edit directly.
 *
 * =========================================================================
 */
#ifndef _SETJMPEX_H_INCLUDED
#define _SETJMPEX_H_INCLUDED

#ifndef _ENABLE_AUTODEPEND
 #pragma read_only_file;
#endif

#ifndef __COMDEF_H_INCLUDED
 #include <_comdef.h>
#endif

#if !defined(_SETJMP_H_INCLUDED_)
 #include <setjmp.h>
#endif

#if defined(__AXP__)

#ifdef __cplusplus
extern "C" {
#endif

_WCRTLINK _NORETURN extern int _setjmpex(jmp_buf __env);

#undef setjmp
#define setjmp(__env)  _setjmpex(__env)

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif

#endif
